### ISSUE TITLE
The "Logs" window is empty even after mining a few blocks

### ISSUE THREAD

**Issue by keroro520** [nervosnetwork/tippy#73]
OS: macOS Catalina 10.15.4, not M1
Google Chrome Version 89.0.4389.128 (Official Build) (x86_64)

The "Logs" window is empty even after mining a few blocks or restarting.

![image](https://user-images.githubusercontent.com/1870648/114971174-60c5b580-9eae-11eb-91ab-697b1c83c341.png)

**Comment by ashchan** [comment]
@keroro520 Thanks for reporting this. I'll confirm and see what's going on.

**Comment by ashchan** [comment]
@keroro520 The Logs page is very limited, it only shows logs popped after you open the page (meaning it doesn't fetch and display history logs). Would that be the reason you saw empty window?

If you keep the Logs window open and let the miner mine a few blocks, would it still be empty?

**Comment by keroro520** [comment]
> @keroro520 The Logs page is very limited, it only shows logs popped after you open the page (meaning it doesn't fetch and display history logs). Would that be the reason you saw empty window?
> 
> If you keep the Logs window open and let the miner mine a few blocks, would it still be empty?

Oh, I see.
When I mine blocks at the Dashboard window and then switch back to Logs window, it is empty;
As I open a new Dashboard window to mine the logs as you suggested, the logs display!

Thanks @ashchan
