### ISSUE TITLE
Install debugger failed

### ISSUE THREAD

**Issue by rev-chaos** [nervosnetwork/tippy#79]
OS: macOS 11.2.3
CPU: Intel Core i9

When I run `brew install gdb --HEAD --build-from-source`, it's failed. The error message is like 

> configure: error: GMP is missing or unusable
> make[1]: *** [configure-gdb] Error 1
> make: *** [all] Error 2

**Comment by rev-chaos** [comment]
This problem has solved.

The version of gdb should upgrade to 10.2.

My solution is:
1. Download gdb-10.2 from https://www.gnu.org/software/gdb/download/
2. Unzip the gdb-10.2 package, and run the following commands inside gdb-10.2
> XX@MacBookPro gdb-10.2$ ./configure
> XX@MacBookPro gdb-10.2$ make -j4
> XX@MacBookPro gdb-10.2$ make install
> XX@MacBookPro gdb-10.2$ gdb -v       
 // make sure the version is 10.2

**Comment by ashchan** [comment]
@rev-chaos Thanks. I'll try gdb 10.2 from homebrew and see if that works too.

**Comment by ashchan** [comment]
Experiment: `brew install gdb --build-from-source` installed the newest `10.2` stable version, but that failed to bring up debugger properly in Tippy. On the other hand, `brew install gdb --HEAD --build-from-source` still works on my Intel Mac.

Closing for now. Will try again when 10.3 comes out.
