### ISSUE TITLE
tippy cannot handle outpoints of cellbase

### ISSUE THREAD

**Issue by rev-chaos** [nervosnetwork/tippy#80]
I  tried to practice a demo, collecting capacity from cellbases to construct a transaction and then sending it to a dev chain built by tippy (here is the [code](https://github.com/rev-chaos/lumos-prac/blob/60c2f77b500f300da69663f4e641e5bd9235f371/index.js#L14) ). However, I have encounter an error which shows:
> Error: JSONRPCError
> Type: server error
> Code: -301
> Message: TransactionFailedToResolve: Resolve failed Unknown([OutPoint(0xace5ea83c478bb866edf122ff862085789158f5cbff155b7bb5f13058555b70800000000)])
> Data: Resolve(Unknown([OutPoint(0xace5ea83c478bb866edf122ff862085789158f5cbff155b7bb5f13058555b70800000000)]))
> (node:6990) UnhandledPromiseRejectionWarning: Error: RPC Returned Error!
> ...

But if I [manually](https://docs.nervos.org/docs/basics/guides/devchain) build a dev chain, everything goes well. 

I wonder if the outpoints of cellbases in tippy are somehow shielded.

**Comment by ashchan** [comment]
I don't think there's any special reason Tippy would make cellbase txs unavailable.

This flow works as we demo:

* Start a devchain setting assembler lock to an address from Neuron wallet
* Start the default miner and mine a few dozens blocks
* Observe the wallet in Neuron, see its balance to increase (from mining rewards)
* Send out tx in Neuron

**Comment by rev-chaos** [comment]
It's not tippy's problem. My codes read the config.json which SECP256K1_BLAKE160 mismatchs with dev chains initiated by tippy.

**Comment by rev-chaos** [comment]
Attention: The hashes of transactions deploying default scripts such as SECP256K1_BLAKE160\SECP256K1_BLAKE160_MULTISIG\DAO in genesis block is inconsistant in each initiation by tippy, while they are consistant when you [manually](https://docs.nervos.org/docs/basics/guides/devchain) initiates a dev chain.

**Comment by ashchan** [comment]
> Attention: The hashes of transactions deploying default scripts such as SECP256K1_BLAKE160\SECP256K1_BLAKE160_MULTISIG\DAO in genesis block is inconsistant in each initiation by tippy, while they are consistant when you [manually](https://docs.nervos.org/docs/basics/guides/devchain) initiates a dev chain.

To be clear that's by design.
