### ISSUE TITLE
用homebrew安装了ttyd和gdb后，点击[debug this script]按钮后tippy要报错

### ISSUE THREAD

**Issue by ashuralyk** [nervosnetwork/tippy#87]
运行环境是WSL 2，安装的版本是prebuild的0.3.0
![image](https://user-images.githubusercontent.com/3871265/120136665-4305a300-c205-11eb-9e97-51805fda4bbc.png)

**Comment by ashchan** [comment]
As on M1 Mac, .Net doesn't seem to respect user path. When homebrew `bin` directory is not in standard location (e.g. `/usr/local/bin` it cannot fork `gdb` or `ttyd`.

**Comment by ashchan** [comment]
Fixed in 6c41693.
