### ISSUE TITLE
tippy里[debug this script]按钮存在有些可以点击有些不能点击的情况

### ISSUE THREAD

**Issue by ashuralyk** [nervosnetwork/tippy#88]
不能点击的情况即使安装了ttyd和gdb在重启tippy后仍然不能点击

不能点击的情况：
![image](https://user-images.githubusercontent.com/3871265/120136816-937d0080-c205-11eb-9153-6456c6d50d24.png)

能点击的情况（但点了会报错）：
![image](https://user-images.githubusercontent.com/3871265/120136848-aabbee00-c205-11eb-85ce-734ea7cffcef.png)

**Comment by ashchan** [comment]
It's a bug, the button on the second screen should be disabled, as Tippy is unable to detect the installed `gdb` and `ttyd` (see #87).
